name: 'blockchain_analytics'
version: '1.0.0'
config-version: 2

profile: 'blockchain'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  blockchain_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
