blockchain_dwh:
  target: prod
  outputs:
    dev:
      type: postgres
      host: postgres-dw
      user: postgres
      password: postgres
      port: 5432
      dbname: blockchain
      schema: public
      threads: 4
    prod:
      type: postgres
      host: postgres-dw
      user: postgres
      password: postgres
      port: 5432
      dbname: blockchain
      schema: public
      threads: 4
