blockchain:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'postgres-dw') }}"
      port: 5432
      user: postgres
      password: postgres
      dbname: blockchain
      schema: public
      threads: 2

