version: 2

models:
  - name: stg_wallets
    description: "Staging model for wallet data"
    data_tests:
      - elementary.volume_anomalies
    columns:
      - name: wallet_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: wallet_address
        description: "Ethereum wallet address"
        data_tests:
          - unique
          - not_null

  - name: stg_transactions
    description: "Staging model for transaction data"
    data_tests:
      - elementary.freshness_anomalies:
          timestamp_column: transaction_timestamp
    columns:
      - name: transaction_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: transaction_hash
        description: "Transaction hash"
        data_tests:
          - unique
          - not_null
      - name: is_error
        description: "Transaction error status"
        data_tests:
          - accepted_values:
              values: [true, false]
      - name: transaction_timestamp
        description: "Time of transaction"
        data_tests:
          - not_null

  - name: int_wallet_transactions
    description: "Intermediate model aggregating wallet transaction statistics"
    data_tests:
      - elementary.all_columns_anomalies
    columns:
      - name: wallet_id
        description: "Wallet identifier"
        data_tests:
          - not_null
      - name: wallet_address
        description: "Wallet address"
        data_tests:
          - not_null

  - name: int_daily_transactions
    description: "Intermediate model for daily transaction aggregation"
    columns:
      - name: transaction_date
        description: "Date of transaction"
        data_tests:
          - unique
          - not_null

  - name: fct_wallet_activity
    description: "Fact table for wallet activity metrics"
    data_tests:
      - elementary.dimension_anomalies:
          dimensions:
            - is_active
    columns:
      - name: wallet_id
        description: "Wallet unique identifier"
        data_tests:
          - unique
          - not_null
          - relationships:
              to: ref('dim_wallets')
              field: wallet_id
      - name: wallet_address
        description: "Wallet public address"
        data_tests:
          - not_null
      - name: is_active
        description: "Flag indicating if wallet has transactions"

  - name: dim_wallets
    description: "Dimension table for wallets with activity metrics"
    columns:
      - name: wallet_id
        description: "Wallet unique identifier"
        data_tests:
          - unique
          - not_null
      - name: actual_tx_count
        description: "Count of actual transactions"
        data_tests:
          - elementary.column_anomalies

  - name: daily_transaction_summary
    description: "Daily aggregated transaction statistics"
    columns:
      - name: transaction_date
        description: "Date of summary"
        data_tests:
          - unique
          - not_null
