version: 2

models:
  - name: stg_wallets
    description: "Staging model for wallet data"
    data_tests:
      - elementary.volume_anomalies:
          severity: warn
    columns:
      - name: wallet_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: wallet_address
        description: "Ethereum wallet address"
        data_tests:
          - unique
          - not_null

  - name: stg_transactions
    description: "Staging model for transaction data"
    data_tests:
      - elementary.freshness_anomalies:
          timestamp_column: transaction_timestamp
      - elementary.event_freshness_anomalies:
          event_timestamp_column: transaction_timestamp
          severity: warn
    columns:
      - name: transaction_id
        description: "Primary key"
        data_tests:
          - unique
          - not_null
      - name: transaction_hash
        description: "Transaction hash"
        data_tests:
          - unique
          - not_null
      - name: is_error
        description: "Transaction error status"
        data_tests:
          - accepted_values:
              values: [true, false]
      - name: transaction_timestamp
        description: "Time of transaction"
        data_tests:
          - not_null

  - name: int_wallet_transactions
    description: "Intermediate model aggregating wallet transaction statistics"
    columns:
      - name: wallet_id
        description: "Wallet identifier"
        data_tests:
          - not_null
      - name: wallet_address
        description: "Wallet address"
        data_tests:
          - not_null

  - name: int_daily_transactions
    description: "Intermediate model for daily transaction aggregation"
    columns:
      - name: transaction_date
        description: "Date of transaction"
        data_tests:
          - unique
          - not_null

  - name: fct_wallet_activity
    description: "Fact table for wallet activity metrics"
    data_tests:
      - elementary.dimension_anomalies:
          dimensions:
            - is_active
          severity: warn
    columns:
      - name: wallet_id
        description: "Wallet unique identifier"
        data_tests:
          - unique
          - not_null
          - relationships:
              to: ref('dim_wallets')
              field: wallet_id
      - name: wallet_address
        description: "Wallet public address"
        data_tests:
          - not_null
      - name: is_active
        description: "Flag indicating if wallet has transactions"

  - name: dim_wallets
    description: "Dimension table for wallets with activity metrics"
    columns:
      - name: wallet_id
        description: "Wallet unique identifier"
        data_tests:
          - unique
          - not_null
      - name: actual_tx_count
        description: "Count of actual transactions"

  - name: daily_transaction_summary
    description: "Daily aggregated transaction statistics"
    columns:
      - name: transaction_date
        description: "Date of summary"
        data_tests:
          - unique
          - not_null

  # ODS layer
  - name: ods_wallets
    description: "ODS layer for wallets enriched with validation and metadata"
    columns:
      - name: wallet_id
        description: "Wallet identifier from raw"
        data_tests:
          - unique
          - not_null
      - name: wallet_address
        description: "Validated wallet address"
        data_tests:
          - not_null
          - unique
      - name: added_at
        description: "Original inserted timestamp"
      - name: last_updated
        description: "Last update timestamp"

  - name: ods_transactions
    description: "ODS layer for transactions with window metrics"
    columns:
      - name: transaction_id
        description: "Primary key from raw"
        data_tests:
          - unique
          - not_null
      - name: transaction_hash
        description: "Hash of transaction"
        data_tests:
          - unique
          - not_null
      - name: transaction_timestamp
        description: "Timestamp of transaction"
        data_tests:
          - not_null
      - name: wallet_address
        description: "Primary wallet address attached to tx"
      - name: cumulative_volume_eth
        description: "Windowed cumulative volume by wallet"
